version: "2"
services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=user@email.com
      - PASS='pas$word'
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
      - TZ=America/Denver
    ports:
      - 8080:80
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Indiana/Indianapolis"
    volumes:
      - /opt/transmission_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/pit/download:/downloads
    restart: always
    network_mode: service:vpn

#  web:
#    image: nginx
#    network_mode: service:vpn